animal = '  mauri wekito  '
print(animal.upper())
print(animal.lower())
print(animal.strip().capitalize())
print(animal.title())
print(animal.strip())
print(animal.replace('wekito', 'webon'))
print('or' in animal)
print(animal.find('mau'))
print('mau' not in animal)
